

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: t40-server-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx" 
    cert-manager.io/cluster-issuer: "letsencrypt-prod" 
spec:
  tls:
  - hosts:
    - api40.my-points.ru
    - web40.my-points.ru
    - insights40.my-points.ru
    secretName: serverpod-tls-t40
  rules:
  - host: "api40.my-points.ru"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: t40-server-service
            port:
              name: api
  - host: "web40.my-points.ru"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: t40-server-service
            port:
              name: web
  - host: "insights40.my-points.ru"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: t40-server-service
            port:
              name: insights
    